/**
 * Regenerates `assets/icons.json`, `assets/icons.popular.json` and
 * `src/model/icon.names.ts` from the `simple-icons` package.
 *
 *   npm run -w packages/core icons
 *
 * **Every** mark in the set, not a curated list. A missing icon used to send an
 * author — usually a model writing a diagram — off to paste raw path data into
 * their `.denji` file, which is the thing this exists to stop.
 *
 * The file is large (megabytes) and so it is generated by the build and kept out
 * of git, exactly like the VS Code grammar. `simple-icons` stays a
 * devDependency: only `dist` is published, so a consumer still pulls in nothing.
 *
 * Note that AWS, Azure, Amazon and Oracle are absent from simple-icons entirely
 * — those companies asked to be removed — so no slug can bring them back.
 * `openjdk` stands in for Java, and `googlecloud` is there.
 */
import { createRequire } from "node:module";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import * as simpleIcons from "simple-icons";

const require_ = createRequire(import.meta.url);

/** Shorthands people actually type. */
const ALIASES: Record<string, string> = {
  postgres: "postgresql",
  pg: "postgresql",
  mongo: "mongodb",
  cassandra: "apachecassandra",
  kafka: "apachekafka",
  nats: "natsdotio",
  spark: "apachespark",
  airflow: "apacheairflow",
  java: "openjdk",
  jvm: "openjdk",
  node: "nodedotjs",
  ts: "typescript",
  js: "javascript",
  golang: "go",
  csharp: "dotnet",
  vue: "vuedotjs",
  nextjs: "nextdotjs",
  next: "nextdotjs",
  k8s: "kubernetes",
  traefik: "traefikproxy",
  envoy: "envoyproxy",
  gcp: "googlecloud",
  otel: "opentelemetry",
};

/** Below this relative luminance a brand colour disappears on a dark surface. */
const DARK_LIMIT = 0.12;
/** Where such a colour is lifted to instead. */
const LIFTED_LIGHTNESS = 0.78;

function channel(v: number): number {
  const c = v / 255;
  return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
}

function luminance(hex: string): number {
  const n = parseInt(hex, 16);
  const [r, g, b] = [(n >> 16) & 255, (n >> 8) & 255, n & 255] as const;
  return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b);
}

/**
 * Lift a near-black brand colour to something visible on a dark background,
 * keeping its hue. Pure black has no hue, so it becomes plain light grey —
 * which is how black wordmarks are conventionally shown in dark mode anyway.
 */
function lighten(hex: string): string {
  const n = parseInt(hex, 16);
  const r = ((n >> 16) & 255) / 255;
  const g = ((n >> 8) & 255) / 255;
  const b = (n & 255) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  const d = max - min;
  const s = d === 0 ? 0 : d / (1 - Math.abs(2 * l - 1));
  let h = 0;
  if (d !== 0) {
    if (max === r) h = ((g - b) / d) % 6;
    else if (max === g) h = (b - r) / d + 2;
    else h = (r - g) / d + 4;
    h *= 60;
    if (h < 0) h += 360;
  }

  const c = (1 - Math.abs(2 * LIFTED_LIGHTNESS - 1)) * s;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = LIFTED_LIGHTNESS - c / 2;
  const seg = Math.floor(h / 60) % 6;
  const rgb = [
    [c, x, 0], [x, c, 0], [0, c, x], [0, x, c], [x, 0, c], [c, 0, x],
  ][seg]!;
  const to = (v: number) =>
    Math.round((v + m) * 255)
      .toString(16)
      .padStart(2, "0");
  return `#${to(rgb[0]!)}${to(rgb[1]!)}${to(rgb[2]!)}`;
}

interface SimpleIcon {
  title: string;
  slug: string;
  hex: string;
  path: string;
}

const registry = simpleIcons as unknown as Record<string, SimpleIcon | undefined>;
const all = Object.values(registry).filter((i): i is SimpleIcon => !!i?.slug && !!i.path);

const icons: Record<string, unknown> = {};
for (const icon of [...all].sort((a, b) => a.slug.localeCompare(b.slug))) {
  const dark = luminance(icon.hex) < DARK_LIMIT ? lighten(icon.hex) : undefined;
  icons[icon.slug] = {
    title: icon.title,
    color: `#${icon.hex.toLowerCase()}`,
    ...(dark ? { darkColor: dark } : {}),
    path: icon.path,
  };
}

const slugs = new Set(Object.keys(icons));
const aliases: Record<string, string> = {};

/**
 * Hand-written shorthands come first — they are the ones people actually type.
 * But a real mark always outranks a shorthand for it: the set grew to carry
 * every brand, and `elastic` stopped being a convenient short way to write
 * `elasticsearch` the day Elastic itself got a mark.
 */
const shadowed: string[] = [];
for (const [from, to] of Object.entries(ALIASES)) {
  if (!slugs.has(to)) throw new Error(`alias ${from} points at missing ${to}`);
  if (slugs.has(from)) {
    shadowed.push(from);
    continue;
  }
  aliases[from] = to;
}

/**
 * `apachespark` answers to `spark`, and so on for the other thirty-four. These
 * are the names a model reaches for first, and the prefix is noise to everyone
 * but Apache. Skipped where the short form is already somebody's slug —
 * `apachehive` may not claim `hive`, which is a different project.
 */
for (const slug of slugs) {
  const short = slug.startsWith("apache") ? slug.slice("apache".length) : "";
  if (short && !slugs.has(short) && !aliases[short]) aliases[short] = slug;
}

/**
 * Simple Icons' own `aka` / `old` names, on the same terms. The guard is not
 * cosmetic: the set lists `terraform` as an alias of OpenTofu, and Terraform is
 * a slug in its own right.
 */
const meta = require_("simple-icons/icons.json") as Array<{
  slug?: string;
  title: string;
  aliases?: { aka?: string[]; old?: string[] };
}>;
const normalize = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");
for (const entry of meta) {
  const target = entry.slug ?? normalize(entry.title);
  if (!slugs.has(target)) continue;
  for (const name of [...(entry.aliases?.aka ?? []), ...(entry.aliases?.old ?? [])]) {
    const from = normalize(name);
    if (from && !slugs.has(from) && !aliases[from]) aliases[from] = target;
  }
}

// `package.json` is not in the package's `exports`, so it cannot be required —
// resolve the entry point and read the manifest beside it instead.
const version = (
  JSON.parse(
    readFileSync(new URL("package.json", pathToFileURL(require_.resolve("simple-icons"))), "utf8"),
  ) as { version: string }
).version;

const sorted = Object.fromEntries(
  Object.entries(aliases).sort(([a], [b]) => a.localeCompare(b)),
);

/**
 * `JSON.parse` of one string, not an object literal of three and a half
 * thousand entries.
 *
 * Not for parse speed — measured, V8 reads the literal a few milliseconds
 * *faster* here and holds 14 MB less, because almost all of the payload is
 * string literals it can internalize against the source it already has. The
 * reasons are on the build side: `tsc` checks one string instead of 3,450
 * entries, a minifier has nothing to walk, and the artefact is one opaque line
 * rather than thousands nobody should ever read.
 */
const embed = (value: unknown) => `JSON.parse(${JSON.stringify(JSON.stringify(value))})`;

const banner = `// Generated by scripts/generate-icons.ts — do not edit by hand, and do not
// commit: the build writes it, and .gitignore keeps it out of the history.
//
// Artwork from Simple Icons (https://simpleicons.org), released under CC0.
// The logos themselves remain trademarks of their respective owners.
`;

/**
 * Names and paths are two files because they have two audiences. Everything
 * that only has to *know* a mark exists — the parser, the builder's validation,
 * a suggestion after a typo — needs 180 KB of names. Only the renderer needs the
 * 4.8 MB of path data. Split, a bundler drops the paths from anything that does
 * not draw: the VS Code extension host runs `checkDiagram` and nothing else, and
 * would otherwise ship five megabytes it can never use.
 */
const names = `${banner}
/** The Simple Icons release these marks were generated from. */
export const ICONSET_VERSION = ${JSON.stringify(version)};

/** Every mark's slug, sorted. */
export const ICON_NAMES: readonly string[] = ${embed(Object.keys(icons))};

/** Its title, for search and for a gallery card. */
export const ICON_TITLES: Record<string, string> = ${embed(
  Object.fromEntries(Object.entries(icons).map(([k, v]) => [k, (v as { title: string }).title])),
)};

/** Shorthands that resolve to one of them. */
export const ICON_ALIASES: Record<string, string> = ${embed(sorted)};
`;

// The banner goes *after* the import, not before it: `tsc` elides an
// `import type` and takes the comment attached to it along, which stripped the
// attribution from the one file that actually carries the artwork.
const data = `import type { Icon } from "./icon.js";

${banner}
/** Every brand mark in the release, by slug. The big one: paths only live here. */
export const ICONS: Record<string, Icon> = ${embed(icons)};
`;

const dir = new URL("../src/model/", import.meta.url);
writeFileSync(fileURLToPath(new URL("icon.names.ts", dir)), names);

/**
 * The artwork goes out **twice**, and on purpose.
 *
 * As a module (`src/model/icon.data.ts`) because that is the only form a browser
 * can have at import time: `resolveIcon` is synchronous, so a bundle that draws a
 * mark has to carry it. The package entry registers it for everyone, which is
 * what keeps `import { toSvg } from "@kxchnev/denji"` drawing logos the way it
 * always did — see the note on compatibility in `src/index.ts`.
 *
 * As a file (`assets/icons.json`) because that is the only form a *product* can
 * load once and share: the CLI reads it off disk without paying for it in
 * `denji check`, and anything that fetches it keeps its own bundle small. Both
 * roads end in the same registry.
 */
const asset = fileURLToPath(new URL("../assets/icons.json", import.meta.url));
mkdirSync(dirname(asset), { recursive: true });
const json = JSON.stringify(icons);
writeFileSync(asset, json);
writeFileSync(fileURLToPath(new URL("icon.data.ts", dir)), data);

if (shadowed.length > 0) {
  console.log(`shorthands dropped, the set now has marks of its own: ${shadowed.join(", ")}`);
}
console.log(
  `wrote ${Object.keys(icons).length} icons and ${Object.keys(sorted).length} aliases ` +
    `from simple-icons ${version} ` +
    `(${(json.length / 1e6).toFixed(1)} MB of paths, as assets/icons.json and as ` +
    `src/model/icon.data.ts, ${Math.round(names.length / 1e3)} KB of names)`,
);
