/**
 * Writes `syntaxes/pwr.tmLanguage.json` from the core's own vocabulary.
 *
 * The `.pwr` grammar is already spelled out in the parser, the CodeMirror
 * tokenizer, the document scan, the autocomplete and `LANGUAGE.md`. A
 * hand-written TextMate grammar would be a sixth copy, and the one that drifts
 * quietest — a highlighter is wrong for months before anyone files it.
 *
 * So the split is: the **shapes of the lines** are written here, because
 * TextMate has no way to express them but regexes, and they mirror the parser's
 * own dispatch order (`arch-parse.ts`, the `startOfLine` chain). The **words**
 * are imported. Add a shape kind or a directive to the core and the highlighter
 * learns it on the next build.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  ARCH_OPERATORS,
  CONTAINER_KIND_NAMES,
  CORNERS,
  DIRECTIVE_NAMES,
  ICON_PROP_NAMES,
  LINK_SCHEMES,
  SHAPE_KIND_NAMES,
  STYLE_PROPS,
  themes,
} from "power";

const OUT = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../syntaxes/pwr.tmLanguage.json",
);

/** `a|b|c`, safe to drop into a pattern. Case-sensitive, like the keywords the
 *  parser matches with `SHAPE_KINDS.has(first)` — `App` really is not a kind. */
const alt = (words: readonly string[]): string => words.map(escapeRe).join("|");

/**
 * The same, but spelled `(?i:…)`.
 *
 * Directive and property names go through `normalizePropName` before they are
 * looked up, so `@rightOf` and `@rightof` are one word and must paint alike.
 */
const altI = (words: readonly string[]): string => `(?i:${alt(words)})`;

const escapeRe = (s: string): string => s.replace(/[.*+?^${}()|[\]\\-]/g, "\\$&");

const KINDS = [...SHAPE_KIND_NAMES, ...CONTAINER_KIND_NAMES];

/** `stroke-width` from `strokeWidth` — the spelling an author is likelier to
 *  write, and one `normalizePropName` strips back down. */
const dashed = (camel: string): string =>
  camel.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase();

/**
 * Every name that may follow an `@`. The parser's own directives plus the style
 * properties, which are written the same way — and each style property is also
 * spellable with dashes (`@stroke-width`), which `normalizePropName` strips.
 */
const STYLE_PROP_NAMES = Object.keys(STYLE_PROPS).flatMap((prop) => {
  const d = dashed(STYLE_PROPS[prop]!.key);
  return d === prop ? [prop] : [prop, d];
});

const DIRECTIVES = altI(longestFirst([...DIRECTIVE_NAMES, ...STYLE_PROP_NAMES]));

/** The schemes `@link` accepts, without their colons — the URL rule adds it. */
const LINK_SCHEME_NAMES = altI(longestFirst(LINK_SCHEMES.map((s) => s.slice(0, -1))));

/** Values that are words rather than numbers, so a typo reads as a typo. */
const CONSTANTS = altI(
  longestFirst([
    ...CORNERS.flatMap((c) => [c.toLowerCase(), dashed(c)]),
    ...Object.keys(themes),
  ]),
);

/** Deduplicated, longest first — an alternation matches left to right, so a
 *  prefix listed early would shadow the longer name it starts. */
function longestFirst(words: readonly string[]): string[] {
  return [...new Set(words)].sort((a, b) => b.length - a.length || a.localeCompare(b));
}

const ID = "[A-Za-z0-9_]+";

/** Repeated wherever a line's tail may carry directives. */
const tail = [{ include: "#directive" }, { include: "#string" }];

/** A `style`/`icon` block, with the property names that belong in this one. */
function block(kind: "style" | "icon", props: readonly string[]): unknown {
  return {
    begin: `^\\s*\\b(${kind})\\b\\s+([A-Za-z][A-Za-z0-9_-]*)\\s*(\\{)`,
    end: "(\\})",
    beginCaptures: {
      1: { name: "keyword.other.block.pwr" },
      2: { name: "entity.name.type.pwr" },
      3: { name: "punctuation.section.block.begin.pwr" },
    },
    endCaptures: { 1: { name: "punctuation.section.block.end.pwr" } },
    name: `meta.block.${kind}.pwr`,
    patterns: [
      { include: "#comment" },
      {
        match: `\\b(?:(${altI(longestFirst(props))})|([A-Za-z][A-Za-z-]*))\\s*(:)([^;}]*)`,
        captures: {
          1: { name: "support.type.property-name.pwr" },
          // Not a property this kind of block takes — the core will reject it.
          2: { name: "invalid.deprecated.pwr" },
          3: { name: "punctuation.separator.key-value.pwr" },
          4: { patterns: [{ include: "#value" }] },
        },
      },
    ],
  };
}

const grammar = {
  $schema:
    "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
  name: "power",
  scopeName: "source.pwr",
  // ⚠️ Generated by scripts/generate-grammar.ts from the core's exported
  // vocabulary. Edit the generator, not this file.
  patterns: [
    { include: "#comment" },
    { include: "#styleBlock" },
    { include: "#iconBlock" },
    { include: "#header" },
    { include: "#close" },
    { include: "#text" },
    { include: "#declaration" },
    { include: "#connection" },
  ],
  repository: {
    // Whole-line only: `app a "X" # note` is a syntax error, not a comment, so
    // this may never match mid-line.
    comment: {
      match: "^\\s*(#|%%).*$",
      name: "comment.line.pwr",
      captures: { 1: { name: "punctuation.definition.comment.pwr" } },
    },

    // A `style x { … }` / `icon x { … }` owns every line up to its own `}` —
    // including one that would otherwise read as a connection (`dash: 6 4`).
    // The two are separate rules because they take different property
    // vocabularies, and a `fill:` in an icon block is an error worth showing.
    styleBlock: block("style", STYLE_PROP_NAMES),
    iconBlock: block("icon", ICON_PROP_NAMES),

    header: {
      begin: "^\\s*\\b(architecture)\\b",
      end: "$",
      beginCaptures: { 1: { name: "keyword.control.pwr" } },
      patterns: tail,
    },

    close: {
      match: "^\\s*(\\})\\s*$",
      captures: { 1: { name: "punctuation.section.block.end.pwr" } },
    },

    // `text "…" @corner(…)` — a free line in a group. It has no id, so it is
    // checked before the declaration rule, exactly as the core dispatches it.
    text: {
      begin: "^\\s*\\b(text)\\b",
      end: "$",
      beginCaptures: { 1: { name: "keyword.control.pwr" } },
      patterns: tail,
    },

    declaration: {
      begin: `^\\s*\\b(${alt(KINDS)})\\b\\s+(${ID})`,
      end: "$",
      beginCaptures: {
        1: { name: "storage.type.pwr" },
        2: { name: "entity.name.type.pwr" },
      },
      patterns: [
        ...tail,
        { match: "\\{", name: "punctuation.section.block.begin.pwr" },
      ],
    },

    // Anything left with an operator in it. The endpoints are references, not
    // declarations, hence a different scope from the id above.
    connection: {
      begin: `^\\s*(${ID})\\s*(${alt(ARCH_OPERATORS)})\\s*(${ID})`,
      end: "$",
      beginCaptures: {
        1: { name: "variable.other.pwr" },
        2: { name: "keyword.operator.pwr" },
        3: { name: "variable.other.pwr" },
      },
      patterns: [
        { include: "#directive" },
        // The label runs from the first `:` to the end of the line — it is not
        // quoted, and it swallows anything that looks like a directive.
        {
          begin: "(:)",
          end: "$",
          beginCaptures: { 1: { name: "punctuation.separator.pwr" } },
          name: "string.unquoted.label.pwr",
        },
      ],
    },

    directive: {
      begin: `(@)(?:(${DIRECTIVES})|([A-Za-z][A-Za-z-]*))\\b\\s*(\\()`,
      end: "(\\))",
      beginCaptures: {
        1: { name: "punctuation.definition.directive.pwr" },
        2: { name: "support.function.pwr" },
        // A name the core does not know. Still painted, but as something else —
        // an unknown directive is an error, and looking identical hides it.
        3: { name: "invalid.deprecated.pwr" },
        4: { name: "punctuation.definition.arguments.begin.pwr" },
      },
      endCaptures: { 1: { name: "punctuation.definition.arguments.end.pwr" } },
      patterns: [{ include: "#value" }],
    },

    value: {
      patterns: [
        // First, and ahead of the colour and number rules: a URL is one token,
        // not a word plus two numbers plus a colour swatch where its `#fragment`
        // happens to read as hex. It ends at `)`, because so does the argument.
        { match: `\\b(?:${LINK_SCHEME_NAMES}):[^\\s)]*`, name: "markup.underline.link.pwr" },
        { match: "#[0-9a-fA-F]{3,8}\\b", name: "constant.other.color.pwr" },
        {
          match: "\\b(rgb|rgba|hsl|hsla)\\b",
          name: "support.function.color.pwr",
        },
        { match: "-?\\b\\d+(\\.\\d+)?\\b", name: "constant.numeric.pwr" },
        { match: `\\b(${CONSTANTS})\\b`, name: "constant.language.pwr" },
        { include: "#string" },
        { match: `\\b${ID}\\b`, name: "variable.parameter.pwr" },
      ],
    },

    string: {
      begin: '"',
      end: '"',
      name: "string.quoted.double.pwr",
      beginCaptures: { 0: { name: "punctuation.definition.string.begin.pwr" } },
      endCaptures: { 0: { name: "punctuation.definition.string.end.pwr" } },
    },
  },
};

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, `${JSON.stringify(grammar, null, 2)}\n`);
console.log(`grammar: ${KINDS.length} kinds, ${ARCH_OPERATORS.length} operators → ${OUT}`);
